/********************************************************************
* ireneDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ireneDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableireneDict();
extern void G__cpp_setup_inheritanceireneDict();
extern void G__cpp_setup_typetableireneDict();
extern void G__cpp_setup_memvarireneDict();
extern void G__cpp_setup_globalireneDict();
extern void G__cpp_setup_memfuncireneDict();
extern void G__cpp_setup_funcireneDict();
extern void G__set_cpp_environmentireneDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/Event.h"
#include "src/ParameterInfo.h"
#include "src/Particle.h"
#include "src/RootWriter.h"
#include "src/SensorHit.h"
#include "src/Service.h"
#include "src/Track.h"
#include "src/Units.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ireneDictLN_TClass;
extern G__linked_taginfo G__ireneDictLN_TBuffer;
extern G__linked_taginfo G__ireneDictLN_TMemberInspector;
extern G__linked_taginfo G__ireneDictLN_TObject;
extern G__linked_taginfo G__ireneDictLN_TNamed;
extern G__linked_taginfo G__ireneDictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__ireneDictLN_string;
extern G__linked_taginfo G__ireneDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ireneDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ireneDictLN_TObjArray;
extern G__linked_taginfo G__ireneDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ireneDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ireneDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__ireneDictLN_irene;
extern G__linked_taginfo G__ireneDictLN_irenecLcLSensorHit;
extern G__linked_taginfo G__ireneDictLN_irenecLcLTrack;
extern G__linked_taginfo G__ireneDictLN_irenecLcLParticle;
extern G__linked_taginfo G__ireneDictLN_TLorentzVector;
extern G__linked_taginfo G__ireneDictLN_irenecLcLEvent;
extern G__linked_taginfo G__ireneDictLN_vectorlEconstsPirenecLcLTrackmUcOallocatorlEconstsPirenecLcLTrackmUgRsPgR;
extern G__linked_taginfo G__ireneDictLN_reverse_iteratorlEvectorlEconstsPirenecLcLTrackmUcOallocatorlEconstsPirenecLcLTrackmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ireneDictLN_vectorlEconstsPirenecLcLParticlemUcOallocatorlEconstsPirenecLcLParticlemUgRsPgR;
extern G__linked_taginfo G__ireneDictLN_reverse_iteratorlEvectorlEconstsPirenecLcLParticlemUcOallocatorlEconstsPirenecLcLParticlemUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ireneDictLN_pairlETLorentzVectorcOdoublegR;
extern G__linked_taginfo G__ireneDictLN_vectorlEpairlETLorentzVectorcOdoublegRcOallocatorlEpairlETLorentzVectorcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__ireneDictLN_vectorlEpairlETLorentzVectorcOdoublegRcOallocatorlEpairlETLorentzVectorcOdoublegRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__ireneDictLN_reverse_iteratorlEvectorlEpairlETLorentzVectorcOdoublegRcOallocatorlEpairlETLorentzVectorcOdoublegRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ireneDictLN_irenecLcLParameterInfo;
extern G__linked_taginfo G__ireneDictLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__ireneDictLN_TVector3;
extern G__linked_taginfo G__ireneDictLN_TRef;
extern G__linked_taginfo G__ireneDictLN_TRefArray;
extern G__linked_taginfo G__ireneDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__ireneDictLN_vectorlEpairlEdoublecOintgRcOallocatorlEpairlEdoublecOintgRsPgRsPgR;
extern G__linked_taginfo G__ireneDictLN_reverse_iteratorlEvectorlEpairlEdoublecOintgRcOallocatorlEpairlEdoublecOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__ireneDictLN_TMatrixTSparseDiaglEdoublegR;

/* STUB derived class for protected member access */
typedef pair<TLorentzVector,double> G__pairlETLorentzVectorcOdoublegR;
typedef vector<pair<TLorentzVector,double>,allocator<pair<TLorentzVector,double> > > G__vectorlEpairlETLorentzVectorcOdoublegRcOallocatorlEpairlETLorentzVectorcOdoublegRsPgRsPgR;
